<?php defined('ROOTPATH') OR exit();
//define autoload path
define("SYSTEMPATH", ROOTPATH.DIRECTORY_SEPARATOR.'system');
define("CONTROLLEPATH",ROOTPATH.DIRECTORY_SEPARATOR.'controller');
define("MODELPATH", ROOTPATH.DIRECTORY_SEPARATOR.'model');
define("VIEWPATH", ROOTPATH.DIRECTORY_SEPARATOR.'view');
define("BASECLASSPATH", SYSTEMPATH.DIRECTORY_SEPARATOR.'class');
define("DBPATH",SYSTEMPATH.DIRECTORY_SEPARATOR.'db');
define("CACHEPATH",SYSTEMPATH.DIRECTORY_SEPARATOR.'cache');
define("HELPERPATH",SYSTEMPATH.DIRECTORY_SEPARATOR.'helper');
define("CONFIGPATH",SYSTEMPATH.DIRECTORY_SEPARATOR.'config');

set_include_path(SYSTEMPATH.PATH_SEPARATOR
    .CONTROLLEPATH.PATH_SEPARATOR
    .MODELPATH.PATH_SEPARATOR
    .VIEWPATH.PATH_SEPARATOR
    .BASECLASSPATH.PATH_SEPARATOR
    .DBPATH.PATH_SEPARATOR
    .CACHEPATH.PATH_SEPARATOR
    .HELPERPATH.PATH_SEPARATOR
    .CONFIGPATH.PATH_SEPARATOR);

spl_autoload_extensions('.php,.inc');
spl_autoload_register();